In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2 # Vectorized Operation
print(result)

[ 1  4  9 16 25]


In [3]:
result + 10

array([11, 14, 19, 26, 35])

In [4]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

result = arr1 + arr2  # Broadcasting arr2 across arr1
print(result)

[[2 4 6]
 [5 7 9]]
