In [1]:
import numpy as np

In [2]:
arr = np.array([1, 3, 4])

In [3]:
arr

array([1, 3, 4])

In [4]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full((4,6), 5)

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [9]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [13]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [14]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [15]:
myarr.shape

(4, 3)

In [16]:
myarr.size

12

In [17]:
myarr.ndim

2

In [29]:
myarr.dtype

dtype('float32')

In [30]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]], dtype="float32")

In [31]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [32]:
n = myarr.astype('float64')

In [33]:
n.dtype

dtype('float64')

In [34]:
myarr.dtype

dtype('float32')

In [35]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [36]:
myarr.shape

(4, 3)

In [37]:
reshaped = myarr.reshape((3, 4))

In [38]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [39]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [40]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])