In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [4]:
flat = arr.flatten()

In [5]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [6]:
flat[0]

np.int64(1)

In [9]:
flat[3: 7]

array([4, 5, 6, 7])

In [10]:
flat[: 5] # same as falt[0: 5]

array([1, 2, 3, 4, 5])

In [11]:
flat[3:] # it will be flat[3: 13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [12]:
flat[3: 13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [14]:
flat[::3]

array([ 1,  4,  7, 11])

In [15]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [21]:
b = flat[3: 7].copy() # this is not a slice because we are using copy method to get the copy

In [22]:
b

array([44444,     5,     6,     7])

In [23]:
b[0] = 4444466

In [24]:
b

array([4444466,       5,       6,       7])

In [25]:
flat

array([    1,     2,     3, 44444,     5,     6,     7,     8,     9,
          11,    12,    13])

In [26]:
arr = np.array([1, 54, 23, 53, 2, 3, 34, 5, 6])

In [27]:
arr[[1, 4, 6]]

array([54,  2, 34])

In [ ]:
arr[